quarkus:
  application:
    name: maestro-api

  http:
    port: 8080

  # REST Configuration
  rest:
    # Enable YAML content type
    media-types:
      - application/x-yaml
      - application/yaml

  log:
    level: INFO
    category:
      "io.maestro": DEBUG

  # Database Configuration
  datasource:
    db-kind: postgresql
    username: ${DB_USERNAME:maestro}
    password: ${DB_PASSWORD:maestro}
    jdbc:
      url: ${DB_URL:jdbc:postgresql://localhost:5432/maestro}
      max-size: 16
      min-size: 2

  # JDBI Configuration (for postgres-repository plugin)
  jdbi:
    install-plugins: true
